name: BlockMaster
version: '${project.version}'
main: net.jeqo.blockmaster.BlockMaster
api-version: '1.20'
authors: [ Gucci Fox ]
description: A unique block creator plugin.
website: https://jeqo.net
commands:
  blockmaster:
    aliases: [bm]
    usage: 'Usage: /blockmaster <command> [args]'
    description: The central command to access the BlockMaster commands.
